ERROR: 2022-08-11 10:36:21,739: Data shape is incorrect!
ERROR: 2022-08-11 10:36:38,893: Data shape is incorrect!
ERROR: 2022-08-11 10:36:38,893: Data shape is incorrect!
ERROR: 2022-08-11 10:40:20,138: Data shape is incorrect!
ERROR: 2022-08-11 10:40:20,138: Data shape is incorrect!
ERROR: 2022-08-11 10:40:20,138: Data shape is incorrect!
ERROR: 2022-08-17 21:24:45,438: Data shape is incorrect!
ERROR: 2022-08-17 21:28:26,995: Data shape is incorrect!
ERROR: 2022-08-17 21:31:51,650: Data shape is incorrect!
ERROR: 2022-08-17 21:31:51,650: Data shape is incorrect!
WARNING: 2022-08-17 21:40:10,941: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.comet-ml.com', port=443): Read timed out. (read timeout=10)")': /api/rest/v2/write/experiment/update-status
WARNING: 2022-08-17 21:40:10,941: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.comet-ml.com', port=443): Read timed out. (read timeout=10)")': /api/rest/v2/write/experiment/update-status
WARNING: 2022-08-17 21:48:38,411: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.comet-ml.com', port=443): Read timed out. (read timeout=10)")': /clientlib/status-report/update
WARNING: 2022-08-17 21:48:38,411: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.comet-ml.com', port=443): Read timed out. (read timeout=10)")': /clientlib/status-report/update
WARNING: 2022-08-17 21:52:16,074: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.comet-ml.com', port=443): Read timed out. (read timeout=10)")': /api/rest/v2/write/experiment/update-status
WARNING: 2022-08-17 21:52:16,074: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.comet-ml.com', port=443): Read timed out. (read timeout=10)")': /api/rest/v2/write/experiment/update-status
WARNING: 2022-08-17 21:57:21,007: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.comet-ml.com', port=443): Read timed out. (read timeout=10)")': /clientlib/status-report/update
WARNING: 2022-08-17 21:57:21,007: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.comet-ml.com', port=443): Read timed out. (read timeout=10)")': /clientlib/status-report/update
WARNING: 2022-08-17 21:57:45,028: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021506BECF40>, 'Connection to www.comet-ml.com timed out. (connect timeout=10)')': /clientlib/status-report/update
WARNING: 2022-08-17 21:57:45,028: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021506BECF40>, 'Connection to www.comet-ml.com timed out. (connect timeout=10)')': /clientlib/status-report/update
WARNING: 2022-08-17 21:58:04,155: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000215068B42E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /clientlib/status-report/update
WARNING: 2022-08-17 21:58:04,155: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000215068B42E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /clientlib/status-report/update
